#!/usr/bin/env bash
# Helper: print pip --require-hashes-compatible lockfile lines for a given list
# of pinned packages, INCLUDING transitive deps.
#
# Uses `pip download` against PyPI inside a clean container. Output is the
# full requirements.lock content - copy/paste into requirements.lock and
# re-run `make audit` to verify the SHA256s independently.
set -euo pipefail

WORKDIR=/tmp/ccc-collect
mkdir -p "$WORKDIR"
cd "$WORKDIR"

# Direct deps - same versions as pyproject.toml
DIRECT=(
  "httpx==0.27.2"
  "pydantic==2.9.2"
  "pyyaml==6.0.2"
  "click==8.1.7"
)

echo "Collecting full dep closure (direct + transitive) for: ${DIRECT[*]}" >&2
pip download "${DIRECT[@]}" \
    --dest "$WORKDIR" \
    --no-binary :none: \
    --quiet \
    --disable-pip-version-check >&2

echo "# C³ requirements.lock - generated by scripts/collect_hashes.sh"
echo "# Install with: pip install --require-hashes --no-deps -r requirements.lock"
echo

# Build the lockfile. For each downloaded file, group by package==version.
declare -A PKG_HASHES
declare -A PKG_VERSION

for f in "$WORKDIR"/*; do
  base=$(basename "$f")
  # Wheel:  pkg-1.2.3-py3-none-any.whl  or  pkg-1.2.3-cp313-cp313-linux_x86_64.whl
  # Sdist:  pkg-1.2.3.tar.gz
  if [[ "$base" == *.whl ]]; then
    # name and version are the first two -separated fields
    name="${base%%-*}"
    rest="${base#*-}"
    ver="${rest%%-*}"
  elif [[ "$base" == *.tar.gz ]]; then
    name="${base%-*}"
    name="${name%-*}"   # not safe for names with multiple dashes
    # simpler: strip .tar.gz then split on last dash
    stem="${base%.tar.gz}"
    ver="${stem##*-}"
    name="${stem%-*}"
  else
    continue
  fi
  # PyPI normalizes underscores back from wheel filenames
  name_norm="${name//_/-}"
  key="${name_norm,,}==${ver}"
  hash=$(sha256sum "$f" | awk '{print $1}')
  PKG_HASHES[$key]+="$hash"$'\n'
  PKG_VERSION[$key]="$ver"
done

# Emit deterministic lockfile sorted by package name
for key in $(printf '%s\n' "${!PKG_HASHES[@]}" | sort); do
  echo -n "$key"
  while IFS= read -r h; do
    [ -z "$h" ] && continue
    echo " \\"
    echo -n "    --hash=sha256:$h"
  done <<< "${PKG_HASHES[$key]}"
  echo
done

echo >&2
echo "Done. Copy stdout above into requirements.lock and run \`make audit\`." >&2
